# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: cimg/node:20.11.0

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          key: v2-dependencies-{{ checksum "yarn.lock" }}

      - run:
          name: Install node dependencies
          command: |
            if [ ! -d node_modules ]; then
              yarn
            fi

      - save_cache:
          key: v2-dependencies-{{ checksum "yarn.lock" }}
          paths:
            - node_modules

      # Ensure TypeScript builds
      - run: yarn run build-ts

      # run tests!
      - run: yarn test

